### ISSUE TITLE
Can't right click signs in lobby 

### ISSUE THREAD

**Issue by MephyMan** [Stealth2800/The-Building-Game#6]
So I made a lobby but only ops can right click the signs to join the game. How does a regular joe right click a sign. It just says 

"You do not have permission to use this command." 

I feel like I need to put this permission somewhere but the main permissions file doesn't work after adding. Running on Ubuntu btw
thebuildinggame.game.play

**Comment by Stealth2800** [comment]
Do you have a permissions plugin installed?  I think you'll have to install one in order to get the permissions working properly.
