### ISSUE TITLE
players can not join

### ISSUE THREAD

**Issue by anemul** [Stealth2800/The-Building-Game#8]
I am running a 1.8 Spigot server , I have GriefPrevention , starterKit , world edit , world guard , perfectbackup , perworldplugins , multiverse-core and multiverse-portals .
Griefprevention is turned off for now . It works for myself the admin/op but not for my regular players . I can not figure out for the life of me why . 
[Uploading arenas.yml.txt…]()
[Uploading config.yml.txt…]()
[Uploading messages.yml.txt…]()
[Uploading signs.yml.txt…]()

**Comment by Stealth2800** [comment]
Any errors in the console when you run the command?

**Comment by anemul** [comment]
Sorry it took me awhile to remember where this was . No errors . How ever I being a new server admin did not think about command line and permissions . After installing bPermissions and spending 2 days on it , they can now type /bg join <arena> and enter the game . However I can not for the life of me figure out how to give them permissions so they can join by clicking the sign .

**Comment by anemul** [comment]
I misread sorry . Yes there was that lead to StarterKit , but I have removed it and no more errors now . My brain is mush trying to figure this out and my monsters not moving or attacking in my survival world .

**Comment by Stealth2800** [comment]
Alright, glad to hear you resolved the issue. Closing.
